import { NextRequest, NextResponse } from "next/server";
import OpenAI from "openai";

const SYSTEM_PROMPT = `You are an expert Certified Flight Instructor (CFI) and AI flight training mentor for FlightForge.ai. Your role is to help student pilots prepare for their Private Pilot checkride.

Guidelines:
- Be encouraging but accurate. Aviation safety depends on correct information.
- Reference the FAR/AIM, ACS standards, and POH when relevant.
- Use the "teach, then quiz" method — explain a concept, then ask a follow-up question.
- When discussing maneuvers, always mention ACS tolerances (altitude ±100ft, heading ±10°, airspeed ±10kts, etc.).
- For weather topics, teach students to decode METARs and TAFs with real-world examples.
- For regulations, cite specific FAR sections (e.g., 14 CFR 91.103).
- Keep responses concise but thorough. Student pilots appreciate clear, structured answers.
- If a student seems confused, break it down into simpler concepts.
- Always emphasize safety, ADM (Aeronautical Decision Making), and risk management.`;

let _openai: OpenAI | null = null;

function getClient(): OpenAI | null {
  if (!process.env.OPENAI_API_KEY) return null;
  if (!_openai) _openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });
  return _openai;
}

const demoResponses: Record<string, string> = {
  default:
    "Great question! In demo mode, I can show you how the AI mentor works. When configured with an OpenAI API key, I provide detailed, aviation-accurate responses tailored to your study needs. Try asking about the four forces of flight, airspace classes, or checkride procedures!",
  forces:
    "The four forces acting on an aircraft in flight are:\n\n1. **Lift** — Generated by the wings, opposes weight. Created by differential pressure (Bernoulli's principle) and Newton's third law.\n2. **Weight** — Gravity pulling the aircraft down. Acts through the center of gravity.\n3. **Thrust** — Produced by the engine/propeller, moves the aircraft forward.\n4. **Drag** — Opposes thrust. Two types: parasite drag (increases with speed) and induced drag (decreases with speed).\n\nIn unaccelerated flight, lift = weight and thrust = drag. Can you tell me what happens to stall speed when we increase the load factor?",
  stall:
    "A stall occurs when the wing exceeds its **critical angle of attack** (typically around 16-18° for most training aircraft). Key points:\n\n- A stall can occur at ANY airspeed, ANY attitude, and ANY power setting\n- The critical angle of attack is constant regardless of weight or load factor\n- Increased load factor increases stall speed: Vs × √(load factor)\n- In a 60° bank turn, load factor is 2G, so stall speed increases by ~41%\n\nWhat are the indications of an approaching stall?",
  metar:
    "Let's decode a METAR! Example:\n\n**KORD 051953Z 27015G25KT 10SM FEW040 SCT080 BKN250 18/07 A3012 RMK AO2**\n\n- **KORD** — Station (Chicago O'Hare)\n- **051953Z** — 5th of the month, 19:53 Zulu\n- **27015G25KT** — Wind from 270° at 15 knots, gusting 25\n- **10SM** — Visibility 10 statute miles\n- **FEW040** — Few clouds at 4,000 ft AGL\n- **SCT080** — Scattered at 8,000 ft\n- **BKN250** — Broken at 25,000 ft (ceiling)\n- **18/07** — Temp 18°C, Dewpoint 7°C\n- **A3012** — Altimeter setting 30.12 inHg\n\nWhat VFR flight rules apply at this location?",
};

function getDemoReply(userMessage: string): string {
  const lower = userMessage.toLowerCase();
  if (lower.includes("force") || lower.includes("lift") || lower.includes("drag")) return demoResponses.forces;
  if (lower.includes("stall") || lower.includes("angle of attack")) return demoResponses.stall;
  if (lower.includes("metar") || lower.includes("taf") || lower.includes("weather")) return demoResponses.metar;
  return demoResponses.default;
}

export async function POST(req: NextRequest) {
  try {
    const { messages, topic, moduleId } = await req.json();

    if (!messages || !Array.isArray(messages)) {
      return NextResponse.json({ error: "Messages required" }, { status: 400 });
    }

    const client = getClient();

    if (!client) {
      const lastMsg = messages[messages.length - 1]?.content || "";
      return NextResponse.json({ reply: getDemoReply(lastMsg) });
    }

    const systemContent = topic
      ? `${SYSTEM_PROMPT}\n\nThe student is currently studying: ${topic}${moduleId ? ` (Module: ${moduleId})` : ""}. Focus your responses on this topic.`
      : SYSTEM_PROMPT;

    const response = await client.chat.completions.create({
      model: "gpt-4o",
      messages: [
        { role: "system", content: systemContent },
        ...messages.slice(-10).map((m: { role: string; content: string }) => ({
          role: m.role as "user" | "assistant",
          content: m.content,
        })),
      ],
      max_tokens: 1000,
      temperature: 0.7,
    });

    const reply = response.choices[0]?.message?.content || "I couldn't generate a response. Please try again.";
    return NextResponse.json({ reply });
  } catch (error) {
    console.error("Chat API error:", error);
    return NextResponse.json({ error: "Failed to generate response" }, { status: 500 });
  }
}
